// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKmel0kCkBZxRpKkBwMjDj0eCQ4jmMLEw',
    appId: '1:979921148562:web:2a37e15718df7b3df1644b',
    messagingSenderId: '979921148562',
    projectId: 'geniaes-57aca',
    authDomain: 'geniaes-57aca.firebaseapp.com',
    storageBucket: 'geniaes-57aca.firebasestorage.app',
    measurementId: 'G-P60CWKFC7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEUbVsbeAln7yAMWIldexADKWgWGIEO5o',
    appId: '1:979921148562:android:3b6637a0c87df4c7f1644b',
    messagingSenderId: '979921148562',
    projectId: 'geniaes-57aca',
    storageBucket: 'geniaes-57aca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPd81nPe-24znfexniivH4dEZrLNK556Q',
    appId: '1:979921148562:ios:b44eef275a8c7e23f1644b',
    messagingSenderId: '979921148562',
    projectId: 'geniaes-57aca',
    storageBucket: 'geniaes-57aca.firebasestorage.app',
    iosBundleId: 'com.geniaes.teachers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPd81nPe-24znfexniivH4dEZrLNK556Q',
    appId: '1:979921148562:ios:fd2eaf7e6ae2d986f1644b',
    messagingSenderId: '979921148562',
    projectId: 'geniaes-57aca',
    storageBucket: 'geniaes-57aca.firebasestorage.app',
    iosBundleId: 'com.example.teacherhubForTutors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKmel0kCkBZxRpKkBwMjDj0eCQ4jmMLEw',
    appId: '1:979921148562:web:e1522165085a0d04f1644b',
    messagingSenderId: '979921148562',
    projectId: 'geniaes-57aca',
    authDomain: 'geniaes-57aca.firebaseapp.com',
    storageBucket: 'geniaes-57aca.firebasestorage.app',
    measurementId: 'G-KHGE5B4DCH',
  );
}
